### PR TITLE
New GUI & Bug fixes

### PR DESCRIPTION
**Pull request by ghost**
Merged & tested all, Added option for mobile or normall webpage, pdf, 7z, bmp fixes, monitor fixand some other stuff... planning to do covers view or something. 

 (still got one pdf error to fix & language bug but that could be months :-) 

Have phun!
  Tristan

### CODE REVIEW

**Comment by ghost** [comment]
Ow, btw do you know how to make the mac disk image work? Currently it only works when go into the package and start it manually... double click on the icon does not but crash... do not know why or how...

Some help is would be wonderfull :-)

**Comment by davide-romanini** [comment]
Wow this is an impressive work :-D
I applied the patch and pushed back on tristan79 branch. I added pylzma to requirements.txt and removed the compiled libunrar.so, you should use `paver libunrar` to compile it on your platform.
The new interface is nice :-D Maybe I should merge with master and release a new version..

I'm a bit skeptical about adding support for more compression formats. I have a strong opinion that comics should be either in CBZ (for scanned ones) or PDF (only for digital ones). Using others is a non sense, compression should be done at image level (and jpeg is still the best format, especially with advanced encoders like mozjpeg) and people should really stop to use something different.

Thanks for your work!

**Comment by ghost** [comment]
I am sick at the moment and not really online for some time. For some
reason my branch gone :-/

Fixed a lot more bugs... encountered many others...  will post later this
month.. played with the gui made it more cartoony..

Fixed 5% of my pdf's not readable, you should check out my fork of the
pypfd2 on github...

https://github.com/Tristan79/PyPDF2

do not know how to integrate that in the source... since not pip...

tried mysql... but got stuck in sqlalchemy (or bad db design)
it works... but only i you never ever delete or move comics...  i tried
created over 80.000 cbz files and mysql speeds it up alot, really made it a
lot faster,.. almost working but... just... i got stuck in the sqlalchemy
and the foreign key, delete,merge thingy... I will post this as a fork...
do you know something about sqlalchemy?

Anyway I will post the main fork when I am online again (not by telephone)
which includes:

And probabaly the nicest function "cache" which I am working very hard on
to get it working. Speeds up page access by storing locally the extracted
images, since my local hdd is a ssd and my comics are on a slow usb2 it is
so much faster...
Also I am trying to implement smart cache, preloading a book if hitting
page 1, preloading +/- 10 pages if hitting a random page and not already
cached...  just to speed things up to use with chunky... it also wakes up
the comic hdd while you use the cache... which result in a very smooth
chunky experience. And maybe an option to use google webp as standard cache
image that will result in smaller images to send when using mobile with
data cap.

But first got to get better.

**Comment by ghost** [comment]
Yes if everybody uses the same standard, it would make live for
programmer's so much simpler. cb7 seen a couple in the wild, never seen the
tar version (cbt) though, which probably can be extracted with the same
lib...

**Comment by ghost** [comment]
The reason for cbt support :) Still sick :-(

https://kat.cr/blog/invisifan/post/52977/

Quote:

  My main concern is more to not mislead people with viewers that don’t
support less common formats — which is why I started _Thread:_ Which comic
reader applications do you prefer?
https://kat.cr/community/show/which-comic-reader-applications-do-you-prefer/
to
see what was being used right now — not totally conclusive, so I think any
comics using new formats should also be in one of the lesser known CB*
formats — in this case, for my uploads I plan to use CBT, which has no
compression, but while you might get up to 3% compression of a JPG in ZIP
or RAR files you get about 0% for WEBP (much less than 1% which only slows
it down with no real space saving) — in fact WEBP based CBZ, etc… files can
be a bit bigger than CBT because of the compression tables & dictionaries
they build but can’t use … and extraction from an uncompressed archive is
faster.

**Comment by davide-romanini** [comment]
CBT/TAR is totally useless to me: you can always create uncompressed zip files and tar are very slow to extract individual files. By the way on modern cpu zip deflate decompression is negligible for our use case so there's no real need for CBT.

**Pull request closed without merging**
