### PR TITLE
Fixed the script src to be protocol independant (http vs https) in the templates.

### PR DESCRIPTION
**Pull request by weidercs**
Fixed the favicon to use webroot and point to the new icon.

### CODE REVIEW

**Comment by bonebox** [comment]
Hey @davide-romanini could you please look at merging this in?  Thanks!

**Comment by bonebox** [comment]
https://github.com/beville/ComicStreamer/issues/24#issuecomment-140710759

**Comment by davide-romanini** [comment]
Merged automatically, didn't do any test.

**Comment by bonebox** [comment]
Just checked it out and it did fix the problem, thanks!

**Pull request merged**
